### PR TITLE
docs: README

### PR DESCRIPTION
**Pull request by wagyu298**
Modify documents in a README file.

### CODE REVIEW

**Comment by wagyu298** [comment]
@ms76 I've modifed the README file that contains changes about https://github.com/otaku-coin/vault-plugin-secrets-ethsign/pull/4#pullrequestreview-1266989094.
I was just hoping that you can give me your feedback on something if you have the time.

**Review by ms76 — COMMENTED** [review]
@wagyu298 I've checked your fixes. I think there is no problem.
However, I think it would be better to remove the description of `Ability to export private keys ("read")` as I think you removed the function.

**Comment by wagyu298** [comment]
@ms76 Thank you for your coding reviews!
I've removed a part of the ALC example. How is this?

**Review by ms76 — APPROVED** [review]
@wagyu298 Thanks for your fix. I think no problem. LGTM!

**Comment by wagyu298** [comment]
@ms76 Thank you for your cooperations!

**Pull request merged**
